# Generated by Django 5.0.6 on 2024-08-21 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appoinment', '0001_initial'),
        ('Doctor', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.availabletime'),
        ),
    ]
